version: '3.9'

services:
  
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=postgres
    networks: 
      - tracker
    volumes:
      - ./postgres-table-init.sql:/docker-entrypoint-initdb.d/postgres-table-init.sql

  tracker_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on: 
      - db
    environment: 
      - USER=postgres
      - HOST=db
      - DATABASE=postgres
      - PASSWORD=todolist
      - PORT=5432
    networks: 
      - tracker

  frontend:
    build: ./react-task-tracker
    ports:
      - "3000:3000"
    depends_on: 
      - tracker_api
    networks: 
      - tracker 

networks: 
  tracker: