name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERPW }}

      - name: Build the Docker image
        run: docker build ./backend --file Dockerfile --tag ${{ secrets.DOCKERUN }}/tracker-api
        
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERUN }}/tracker-api

      - name: Build the Docker image
        run: docker build ./react-task-tracker --file Dockerfile --tag ${{ secrets.DOCKERUN }}/tracker-app
        
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERUN }}/tracker-app
